#!/bin/bash


# compile interfaces
echo "Compiling interfaces..."
tsc interfaces/product.ts
tsc interfaces/report.ts
tsc interfaces/trive-subscription.ts
tsc interfaces/user-image.ts
tsc interfaces/user.ts
tsc interfaces/user-billing-key.ts
tsc interfaces/vehicle.ts
echo "...finished compiling interfaces"

# compile main library code
echo "Compiling main library code..."
tsc index.ts
echo "...finished compiling main library code"

# compile test helper code
echo "Compiling test helper code..."
tsc test/data/product.ts
tsc test/data/report.ts
tsc test/data/subscription.ts
tsc test/data/user.ts
tsc test/data/user-billing-key.ts
tsc test/data/vehicle.ts
echo "...finished compiling test helper code"

echo "Completely finished with Typescript compilation!"

echo "Running unit tests..."
npm test
echo "...finished running all unit tests!"
